thisworks = "Nurdaulet"
this_works = "Nurdaulet"
_this_works = "Nurdaulet"
thisWorks = "Nurdaulet"
THISWORKS = "Nurdaulet"
thisworks2 = "Nurdaulet"
"""
2thisdoesnotwork = "Nurdaulet"
this-does-not-work = "Nurdaulet"
this does not work = "Nurdaulet"
"""